services:
  - type: web
    name: farmasyst-north-frontend
    runtime: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://farmasyst-backend.onrender.com"
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html